"""
JWT Test Repository - Data access layer for User model.

Handles all database operations for user data.
This repository queries the shared database where NextAuth stores user information.

References:
- SQLAlchemy 2.0 Async Guide: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html
- Repository Pattern: https://martinfowler.com/eaaCatalog/repository.html
"""

import logging
from typing import Sequence

from sqlalchemy import func, select
from sqlalchemy import exists as sql_exists
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.user import User

logger = logging.getLogger(__name__)


class UserRepository:
    """
    Repository for User database operations.

    Provides async methods for querying user data from the database.
    All methods use SQLAlchemy 2.0 async syntax with explicit session management.

    Usage:
        async with AsyncSessionLocal() as session:
            repo = UserRepository(session)
            user = await repo.get_by_id("user_id")
    """

    def __init__(self, session: AsyncSession) -> None:
        """
        Initialize the repository with a database session.

        Args:
            session: SQLAlchemy async session for database operations
        """
        self.session = session

    async def get_by_id(self, user_id: str) -> User | None:
        """
        Retrieve a user by their unique ID.

        Args:
            user_id: The user's CUID (generated by Prisma)

        Returns:
            User | None: The user if found, None otherwise
        """
        logger.debug(f"Fetching user by ID: {user_id}")

        stmt = select(User).where(User.id == user_id)
        result = await self.session.execute(stmt)
        user = result.scalar_one_or_none()

        if user:
            logger.debug(f"Found user: {user.email}")
        else:
            logger.debug(f"User not found: {user_id}")

        return user

    async def get_by_email(self, email: str) -> User | None:
        """
        Retrieve a user by their email address.

        Args:
            email: The user's email address

        Returns:
            User | None: The user if found, None otherwise
        """
        logger.debug(f"Fetching user by email: {email}")

        stmt = select(User).where(User.email == email)
        result = await self.session.execute(stmt)
        user = result.scalar_one_or_none()

        if user:
            logger.debug(f"Found user: {user.id}")
        else:
            logger.debug(f"User not found with email: {email}")

        return user

    async def get_all(self, limit: int = 100, offset: int = 0) -> Sequence[User]:
        """
        Retrieve all users with pagination.

        Args:
            limit: Maximum number of users to return (default: 100)
            offset: Number of users to skip (default: 0)

        Returns:
            Sequence[User]: List of users
        """
        logger.debug(f"Fetching users: limit={limit}, offset={offset}")

        stmt = select(User).limit(limit).offset(offset).order_by(User.created_at.desc())
        result = await self.session.execute(stmt)
        users = result.scalars().all()

        logger.debug(f"Found {len(users)} users")
        return users

    async def count(self) -> int:
        """
        Count total number of users.

        Returns:
            int: Total user count
        """
        stmt = select(func.count()).select_from(User)
        result = await self.session.execute(stmt)
        count = result.scalar_one()

        logger.debug(f"Total users: {count}")
        return count

    async def exists(self, user_id: str) -> bool:
        """
        Check if a user exists by ID.

        Args:
            user_id: The user's CUID

        Returns:
            bool: True if user exists, False otherwise
        """
        stmt = select(sql_exists().where(User.id == user_id))
        result = await self.session.execute(stmt)
        return result.scalar_one()
