"""add_is_publishable_field

Revision ID: 026b33487ab5
Revises: 6ccc3fbe146a
Create Date: 2026-01-11 18:41:13.707363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026b33487ab5'
down_revision: Union[str, Sequence[str], None] = '6ccc3fbe146a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('feeds', sa.Column('is_publishable', sa.Boolean(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE feeds SET is_publishable = false WHERE is_publishable IS NULL")

    # Make column not nullable
    op.alter_column('feeds', 'is_publishable', nullable=False)

    # Create index
    op.create_index(op.f('ix_feeds_is_publishable'), 'feeds', ['is_publishable'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feeds_is_publishable'), table_name='feeds')
    op.drop_column('feeds', 'is_publishable')
    # ### end Alembic commands ###
