"""Add stage verification fields

Revision ID: 6ccc3fbe146a
Revises: 19464169de84
Create Date: 2026-01-11 16:20:13.941808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccc3fbe146a'
down_revision: Union[str, Sequence[str], None] = '19464169de84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('verification_error', sa.Boolean(), nullable=False))
    op.add_column('feeds', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('feeds', sa.Column('stages_completed', sa.Integer(), nullable=False))
    op.add_column('feeds', sa.Column('skipped_at_stage', sa.Integer(), nullable=True))
    op.add_column('feeds', sa.Column('skip_reason', sa.String(length=255), nullable=True))
    op.add_column('feeds', sa.Column('processing_time_ms', sa.Integer(), nullable=False))
    op.add_column('feeds', sa.Column('tokens_used', sa.Integer(), nullable=False))
    op.add_column('feeds', sa.Column('stage1_completed', sa.Boolean(), nullable=False))
    op.add_column('feeds', sa.Column('stage1_score', sa.Float(), nullable=True))
    op.add_column('feeds', sa.Column('stage1_has_location', sa.Boolean(), nullable=False))
    op.add_column('feeds', sa.Column('stage1_is_duplicate', sa.Boolean(), nullable=False))
    op.add_column('feeds', sa.Column('stage1_subjectivity', sa.Float(), nullable=True))
    op.add_column('feeds', sa.Column('stage1_fake_prob', sa.Float(), nullable=True))
    op.add_column('feeds', sa.Column('stage2_completed', sa.Boolean(), nullable=False))
    op.add_column('feeds', sa.Column('stage2_check_worthy', sa.Float(), nullable=True))
    op.add_column('feeds', sa.Column('stage2_has_fact_check', sa.Boolean(), nullable=False))
    op.add_column('feeds', sa.Column('stage2_fact_check_ratings', sa.Text(), nullable=True))
    op.add_column('feeds', sa.Column('stage3_completed', sa.Boolean(), nullable=False))
    op.add_column('feeds', sa.Column('stage3_verdict', sa.String(length=50), nullable=True))
    op.add_column('feeds', sa.Column('stage3_confidence', sa.Float(), nullable=True))
    op.add_column('feeds', sa.Column('stage3_reasoning', sa.Text(), nullable=True))
    op.drop_column('feeds', 'fake_probability')
    op.drop_column('feeds', 'subjectivity_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('subjectivity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('fake_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('feeds', 'stage3_reasoning')
    op.drop_column('feeds', 'stage3_confidence')
    op.drop_column('feeds', 'stage3_verdict')
    op.drop_column('feeds', 'stage3_completed')
    op.drop_column('feeds', 'stage2_fact_check_ratings')
    op.drop_column('feeds', 'stage2_has_fact_check')
    op.drop_column('feeds', 'stage2_check_worthy')
    op.drop_column('feeds', 'stage2_completed')
    op.drop_column('feeds', 'stage1_fake_prob')
    op.drop_column('feeds', 'stage1_subjectivity')
    op.drop_column('feeds', 'stage1_is_duplicate')
    op.drop_column('feeds', 'stage1_has_location')
    op.drop_column('feeds', 'stage1_score')
    op.drop_column('feeds', 'stage1_completed')
    op.drop_column('feeds', 'tokens_used')
    op.drop_column('feeds', 'processing_time_ms')
    op.drop_column('feeds', 'skip_reason')
    op.drop_column('feeds', 'skipped_at_stage')
    op.drop_column('feeds', 'stages_completed')
    op.drop_column('feeds', 'error_message')
    op.drop_column('feeds', 'verification_error')
    # ### end Alembic commands ###
