"""add_cluster_id_to_events

Revision ID: 800e160bd2ed
Revises: d4e5f6a7b8c9
Create Date: 2026-01-21 12:18:03.475048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800e160bd2ed'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identifier', 'token'),
    sa.UniqueConstraint('identifier', 'token', name='verification_tokens_identifier_token_key')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.String(length=25), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('session_state', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=25), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.add_column('articles', sa.Column('is_corrected', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('articles', sa.Column('correction_note', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('original_content_snapshot', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_channels_credibility_score'), table_name='channels')
    op.drop_index(op.f('ix_channels_tier'), table_name='channels')
    op.add_column('events', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_events_embedding_cosine'), table_name='events', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_events_cluster_id'), 'events', ['cluster_id'], unique=False)
    op.add_column('feeds', sa.Column('stage2_verdict', sa.String(length=50), nullable=True))
    op.add_column('feeds', sa.Column('stage2_confidence', sa.Float(), nullable=True))
    op.add_column('feeds', sa.Column('stage2_evidence_summary', sa.Text(), nullable=True))
    op.drop_column('feeds', 'stage2_fact_check_ratings')
    op.drop_column('feeds', 'stage2_has_fact_check')
    op.drop_column('feeds', 'stage2_check_worthy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('stage2_check_worthy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feeds', sa.Column('stage2_has_fact_check', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('feeds', sa.Column('stage2_fact_check_ratings', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('feeds', 'stage2_evidence_summary')
    op.drop_column('feeds', 'stage2_confidence')
    op.drop_column('feeds', 'stage2_verdict')
    op.drop_index(op.f('ix_events_cluster_id'), table_name='events')
    op.create_index(op.f('ix_events_embedding_cosine'), 'events', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('events', 'cluster_id')
    op.create_index(op.f('ix_channels_tier'), 'channels', ['tier'], unique=False)
    op.create_index(op.f('ix_channels_credibility_score'), 'channels', ['credibility_score'], unique=False)
    op.drop_column('articles', 'original_content_snapshot')
    op.drop_column('articles', 'corrected_at')
    op.drop_column('articles', 'correction_note')
    op.drop_column('articles', 'is_corrected')
    op.drop_table('sessions')
    op.drop_table('items')
    op.drop_table('accounts')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
