"""
JWT Guard - Authentication interceptor for FastAPI routes.

Validates JWT tokens generated by NextAuth.js (Auth.js) from the frontend.
Uses the fastapi-nextauth-jwt library for seamless token decryption and validation.

This guard follows the NestJS guard pattern where authentication is checked
before the request reaches the controller.

References:
- https://pypi.org/project/fastapi-nextauth-jwt/
- https://github.com/TCatshoek/fastapi-nextauth-jwt
- https://docs.nestjs.com/guards (conceptual reference)
"""

import logging
from dataclasses import dataclass
from typing import Annotated

from fastapi import Depends, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from fastapi_nextauth_jwt import NextAuthJWT

from app.core.config import settings

logger = logging.getLogger(__name__)


# ============================================================
# JWT Token Decoder using fastapi-nextauth-jwt
# ============================================================

_jwt_decoder: NextAuthJWT | None = None


def get_jwt_decoder() -> NextAuthJWT:
    """
    Get or create the NextAuthJWT decoder instance.

    The decoder uses:
    - AUTH_SECRET: The encryption key (must match frontend's AUTH_SECRET)
    - A256CBC-HS512: Default encryption algorithm used by Auth.js v5

    Returns:
        NextAuthJWT: Configured JWT decoder instance

    Raises:
        ValueError: If AUTH_SECRET is not configured
    """
    global _jwt_decoder

    if _jwt_decoder is None:
        if not settings.AUTH_SECRET:
            raise ValueError(
                "AUTH_SECRET is not configured. "
                "Set AUTH_SECRET in .env to match your frontend's AUTH_SECRET."
            )

        _jwt_decoder = NextAuthJWT(
            secret=settings.AUTH_SECRET,
            # CSRF is handled by NextAuth on the frontend, so we disable it here
            # The backend validates the JWT signature/encryption which is sufficient
            csrf_prevention_enabled=False,
            # Check token expiration
            check_expiry=True,
        )

    return _jwt_decoder


# ============================================================
# Data Classes for Type-Safe Token Payload
# ============================================================


@dataclass
class JWTPayload:
    """
    Decoded JWT token payload from NextAuth.

    Contains user information embedded in the JWT by NextAuth's jwt() callback.
    The exact fields depend on what's stored in the frontend's jwt callback.

    Attributes:
        user_id: User identifier from token.id
        email: User email from token.email
        name: User name from token.name
        role: User role from token.role (custom field added in jwt callback)
        exp: Token expiration timestamp
        iat: Token issued at timestamp
        jti: JWT ID
    """

    user_id: str
    email: str | None
    name: str | None
    role: str
    exp: int | None = None
    iat: int | None = None
    jti: str | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "JWTPayload":
        """
        Create JWTPayload from decoded JWT dictionary.

        Args:
            data: Decoded JWT payload dictionary

        Returns:
            JWTPayload: Structured token payload
        """
        return cls(
            user_id=data.get("id", data.get("sub", "")),
            email=data.get("email"),
            name=data.get("name"),
            role=data.get("role", "USER"),
            exp=data.get("exp"),
            iat=data.get("iat"),
            jti=data.get("jti"),
        )


# ============================================================
# HTTP Bearer Token Extractor
# ============================================================

bearer_scheme = HTTPBearer(
    scheme_name="Bearer",
    description="NextAuth JWT token from the Authorization header",
    auto_error=False,
)


async def get_token_from_header(
    credentials: Annotated[HTTPAuthorizationCredentials | None, Depends(bearer_scheme)],
) -> str | None:
    """
    Extract JWT token from Authorization header.

    The frontend should send the token as:
    Authorization: Bearer <jwt_token>

    Args:
        credentials: HTTP Authorization credentials

    Returns:
        str | None: The JWT token if present, None otherwise
    """
    if credentials is None:
        return None

    return credentials.credentials


async def get_token_from_cookie(request: Request) -> str | None:
    """
    Extract JWT token from NextAuth session cookie.

    NextAuth stores the JWT in a cookie with one of these names:
    - __Secure-authjs.session-token (production/HTTPS)
    - authjs.session-token (development/HTTP)
    - __Secure-next-auth.session-token (NextAuth v4)
    - next-auth.session-token (NextAuth v4 development)

    Args:
        request: FastAPI request object

    Returns:
        str | None: The JWT token if found in cookies, None otherwise
    """
    cookie_names = [
        "__Secure-authjs.session-token",
        "authjs.session-token",
        "__Secure-next-auth.session-token",
        "next-auth.session-token",
    ]

    for cookie_name in cookie_names:
        token = request.cookies.get(cookie_name)
        if token:
            logger.debug(f"Found JWT token in cookie: {cookie_name}")
            return token

    return None


# ============================================================
# JWT Validation Dependencies (Guards)
# ============================================================


async def get_current_user_optional(
    request: Request,
    token_from_header: Annotated[str | None, Depends(get_token_from_header)],
) -> JWTPayload | None:
    """
    Get current user from JWT token (optional).

    Attempts to extract and validate JWT from:
    1. Authorization header (Bearer token)
    2. Session cookie (NextAuth cookie)

    This guard does NOT raise an error if no token is found.
    Use this for routes that should work for both authenticated and anonymous users.

    Args:
        request: FastAPI request
        token_from_header: Token extracted from Authorization header

    Returns:
        JWTPayload | None: Decoded token payload or None if not authenticated
    """
    token = token_from_header or await get_token_from_cookie(request)

    if not token:
        return None

    try:
        decoder = get_jwt_decoder()
        payload = await decoder(request)
        return JWTPayload.from_dict(payload)
    except Exception as e:
        logger.warning(f"JWT validation failed: {e}")
        return None


async def get_current_user(
    request: Request,
    token_from_header: Annotated[str | None, Depends(get_token_from_header)],
) -> JWTPayload:
    """
    Get current user from JWT token (required).

    Validates the JWT token and returns the payload.
    Raises HTTPException if:
    - No token is provided
    - Token is invalid or expired
    - Token cannot be decrypted

    Use this guard for protected routes that REQUIRE authentication.

    Args:
        request: FastAPI request
        token_from_header: Token extracted from Authorization header

    Returns:
        JWTPayload: Decoded token payload

    Raises:
        HTTPException: 401 if not authenticated or token invalid
    """
    token = token_from_header or await get_token_from_cookie(request)

    if not token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authenticated. Please provide a valid JWT token.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    try:
        decoder = get_jwt_decoder()
        payload = await decoder(request)
        return JWTPayload.from_dict(payload)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"JWT validation error: {e}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid or expired token: {str(e)}",
            headers={"WWW-Authenticate": "Bearer"},
        )


async def get_current_admin(
    current_user: Annotated[JWTPayload, Depends(get_current_user)],
) -> JWTPayload:
    """
    Get current user and verify admin role (required).

    Validates that the authenticated user has ADMIN role.
    Use this guard for admin-only routes.

    Args:
        current_user: Authenticated user from get_current_user

    Returns:
        JWTPayload: Decoded token payload (verified as admin)

    Raises:
        HTTPException: 403 if user is not an admin
    """
    if current_user.role != "ADMIN":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin privileges required.",
        )

    return current_user


# ============================================================
# Type Aliases for Dependency Injection
# ============================================================

# Optional authentication - returns None if not authenticated
CurrentUserOptional = Annotated[JWTPayload | None, Depends(get_current_user_optional)]

# Required authentication - raises 401 if not authenticated
CurrentUser = Annotated[JWTPayload, Depends(get_current_user)]

# Admin authentication - raises 401/403 if not authenticated or not admin
CurrentAdmin = Annotated[JWTPayload, Depends(get_current_admin)]
