"""
JWT Guard - Authentication interceptor for FastAPI routes.

Validates JWT tokens generated by NextAuth.js (Auth.js) from the frontend.
Uses fastapi-nextauth-jwt library to decode NextAuth's encrypted JWE tokens.

NextAuth uses JWE (JSON Web Encryption) by default with A256CBC-HS512 algorithm.
This library handles the decryption using the AUTH_SECRET.

Supports both:
1. Cookie-based authentication (authjs.session-token cookie)
2. Bearer token authentication (Authorization: Bearer <token>)

This guard follows the NestJS guard pattern where authentication is checked
before the request reaches the controller.

References:
- https://github.com/nicobytes/fastapi-nextauth-jwt
- https://authjs.dev/concepts/session-strategies
- https://docs.nestjs.com/guards (conceptual reference)
"""

import json
import logging
from dataclasses import dataclass
from json import JSONDecodeError
from typing import Annotated

from fastapi import Depends, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from fastapi_nextauth_jwt import NextAuthJWT
from fastapi_nextauth_jwt.exceptions import (
    InvalidTokenError,
    MissingTokenError,
    TokenExpiredException,
)
from fastapi_nextauth_jwt.fastapi_nextauth_jwt import check_expiry
from jose import jwe
from jose.exceptions import JWEError

from app.core.config import settings

logger = logging.getLogger(__name__)


# ============================================================
# NextAuth JWT Decoder (Singleton)
# ============================================================

_jwt_decoder: NextAuthJWT | None = None


def get_jwt_decoder() -> NextAuthJWT:
    """
    Get or create the NextAuth JWT decoder singleton.

    Uses AUTH_SECRET from settings to decrypt JWE tokens.
    The same AUTH_SECRET must be used in the frontend's NextAuth configuration.

    Returns:
        NextAuthJWT: Configured JWT decoder instance
    """
    global _jwt_decoder
    if _jwt_decoder is None:
        if not settings.AUTH_SECRET:
            raise ValueError(
                "AUTH_SECRET is not configured. "
                "Set AUTH_SECRET in .env to match your frontend's AUTH_SECRET."
            )
        _jwt_decoder = NextAuthJWT(
            secret=settings.AUTH_SECRET,
            csrf_prevention_enabled=False,  # CSRF handled by frontend
            check_expiry=True,  # Check token expiration
        )
    return _jwt_decoder


def decode_jwe_token(token: str, should_check_expiry: bool = True) -> dict:
    """
    Manually decrypt a JWE token using the same key as NextAuthJWT.

    This function allows decrypting tokens from Authorization header,
    not just from cookies.

    Args:
        token: The encrypted JWE token string
        should_check_expiry: Whether to check token expiration

    Returns:
        dict: Decoded token payload

    Raises:
        InvalidTokenError: If token is invalid
        TokenExpiredException: If token has expired
    """
    decoder = get_jwt_decoder()

    try:
        # Use the same key that NextAuthJWT uses
        decrypted_token_string = jwe.decrypt(token, decoder.key)
        payload = json.loads(decrypted_token_string)
    except (JWEError, JSONDecodeError) as e:
        logger.error(f"JWE decryption failed: {e}")
        raise InvalidTokenError(status_code=401, message="Invalid JWT format")

    if should_check_expiry:
        if "exp" not in payload:
            raise InvalidTokenError(status_code=401, message="Invalid JWT format, missing exp")
        check_expiry(payload["exp"])

    return payload


# ============================================================
# Data Classes for Type-Safe Token Payload
# ============================================================


@dataclass
class JWTPayload:
    """
    Decoded JWT token payload from NextAuth.

    Contains user information embedded in the JWT by NextAuth's jwt() callback.
    The exact fields depend on what's stored in the frontend's jwt callback.

    Attributes:
        user_id: User identifier from token.id
        email: User email from token.email
        name: User name from token.name
        role: User role from token.role (custom field added in jwt callback)
        exp: Token expiration timestamp
        iat: Token issued at timestamp
    """

    user_id: str
    email: str | None
    name: str | None
    role: str
    exp: int | None = None
    iat: int | None = None

    @classmethod
    def from_dict(cls, data: dict) -> "JWTPayload":
        """
        Create JWTPayload from decoded JWT dictionary.

        Args:
            data: Decoded JWT payload dictionary

        Returns:
            JWTPayload: Structured token payload
        """
        return cls(
            user_id=data.get("id", data.get("sub", "")),
            email=data.get("email"),
            name=data.get("name"),
            role=data.get("role", "USER"),
            exp=data.get("exp"),
            iat=data.get("iat"),
        )


# ============================================================
# HTTP Bearer Token Extractor
# ============================================================

bearer_scheme = HTTPBearer(
    scheme_name="Bearer",
    description="NextAuth JWT token from the Authorization header",
    auto_error=False,
)


async def get_token_from_header(
    credentials: Annotated[HTTPAuthorizationCredentials | None, Depends(bearer_scheme)],
) -> str | None:
    """
    Extract JWT token from Authorization header.

    The frontend should send the token as:
    Authorization: Bearer <jwt_token>

    Args:
        credentials: HTTP Authorization credentials

    Returns:
        str | None: The JWT token if present, None otherwise
    """
    if credentials is None:
        return None

    return credentials.credentials


async def get_token_from_cookie(request: Request) -> str | None:
    """
    Extract JWT token from NextAuth session cookie.

    NextAuth stores the JWT in a cookie with one of these names:
    - __Secure-authjs.session-token (production/HTTPS)
    - authjs.session-token (development/HTTP)
    - __Secure-next-auth.session-token (NextAuth v4)
    - next-auth.session-token (NextAuth v4 development)

    Args:
        request: FastAPI request object

    Returns:
        str | None: The JWT token if found in cookies, None otherwise
    """
    cookie_names = [
        "__Secure-authjs.session-token",
        "authjs.session-token",
        "__Secure-next-auth.session-token",
        "next-auth.session-token",
    ]

    for cookie_name in cookie_names:
        token = request.cookies.get(cookie_name)
        if token:
            logger.debug(f"Found JWT token in cookie: {cookie_name}")
            return token

    return None


# ============================================================
# JWT Validation Dependencies (Guards)
# ============================================================


async def get_current_user_optional(
    request: Request,
    token_from_header: Annotated[str | None, Depends(get_token_from_header)],
) -> JWTPayload | None:
    """
    Get current user from JWT token (optional).

    Attempts to extract and validate JWT from:
    1. Authorization header (Bearer token)
    2. Session cookie (NextAuth cookie)

    This guard does NOT raise an error if no token is found.
    Use this for routes that should work for both authenticated and anonymous users.

    Args:
        request: FastAPI request
        token_from_header: Token extracted from Authorization header

    Returns:
        JWTPayload | None: Decoded token payload or None if not authenticated
    """
    # Check if we have a token from header or cookie
    token_from_cookie = await get_token_from_cookie(request)
    token = token_from_header or token_from_cookie

    if not token:
        return None

    try:
        # If token came from header, use manual decryption
        # If token came from cookie, use the NextAuthJWT callable
        if token_from_header:
            payload = decode_jwe_token(token_from_header)
        else:
            decoder = get_jwt_decoder()
            payload = decoder(request)

        return JWTPayload.from_dict(payload)
    except (InvalidTokenError, TokenExpiredException, MissingTokenError) as e:
        logger.warning(f"JWT validation failed: {e}")
        return None
    except Exception as e:
        logger.warning(f"Unexpected error during JWT validation: {e}")
        return None


async def get_current_user(
    request: Request,
    token_from_header: Annotated[str | None, Depends(get_token_from_header)],
) -> JWTPayload:
    """
    Get current user from JWT token (required).

    Validates the JWT token and returns the payload.
    Raises HTTPException if:
    - No token is provided
    - Token is invalid or expired
    - Token decryption fails

    Use this guard for protected routes that REQUIRE authentication.

    Args:
        request: FastAPI request
        token_from_header: Token extracted from Authorization header

    Returns:
        JWTPayload: Decoded token payload

    Raises:
        HTTPException: 401 if not authenticated or token invalid
    """
    # Check if we have a token from header or cookie
    token_from_cookie = await get_token_from_cookie(request)
    token = token_from_header or token_from_cookie

    if not token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authenticated. Please provide a valid JWT token.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    try:
        # If token came from header, use manual decryption
        # If token came from cookie, use the NextAuthJWT callable
        if token_from_header:
            payload = decode_jwe_token(token_from_header)
        else:
            decoder = get_jwt_decoder()
            payload = decoder(request)

        return JWTPayload.from_dict(payload)
    except TokenExpiredException:
        logger.error("JWT token has expired")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token has expired. Please log in again.",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except InvalidTokenError as e:
        logger.error(f"Invalid JWT token: {e}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token. Please log in again.",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except MissingTokenError:
        logger.error("Missing JWT token")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authenticated. Please provide a valid JWT token.",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except Exception as e:
        logger.error(f"Unexpected error during JWT validation: {e}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token validation failed",
            headers={"WWW-Authenticate": "Bearer"},
        )


async def get_current_admin(
    current_user: Annotated[JWTPayload, Depends(get_current_user)],
) -> JWTPayload:
    """
    Get current user and verify admin role (required).

    Validates that the authenticated user has ADMIN role.
    Use this guard for admin-only routes.

    Args:
        current_user: Authenticated user from get_current_user

    Returns:
        JWTPayload: Decoded token payload (verified as admin)

    Raises:
        HTTPException: 403 if user is not an admin
    """
    if current_user.role != "ADMIN":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin privileges required.",
        )

    return current_user


# ============================================================
# Type Aliases for Dependency Injection
# ============================================================

# Optional authentication - returns None if not authenticated
CurrentUserOptional = Annotated[JWTPayload | None, Depends(get_current_user_optional)]

# Required authentication - raises 401 if not authenticated
CurrentUser = Annotated[JWTPayload, Depends(get_current_user)]

# Admin authentication - raises 401/403 if not authenticated or not admin
CurrentAdmin = Annotated[JWTPayload, Depends(get_current_admin)]
