"""
Account model - mirrors the frontend Prisma Account schema.

This model stores OAuth provider account information linked to users.
Used by NextAuth.js to manage OAuth connections (Google, Discord, Kakao, etc.)
"""

from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Account(Base):
    """
    Account model matching the frontend Prisma Account schema.

    Table name: 'accounts' (matches Prisma @@map("accounts"))

    Stores OAuth provider credentials and tokens for each user.
    A user can have multiple accounts (one per OAuth provider).
    """

    __tablename__ = "accounts"

    # Primary key - CUID generated by Prisma
    id: Mapped[str] = mapped_column(String(25), primary_key=True)

    # Foreign key to User
    user_id: Mapped[str] = mapped_column(
        String(25),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        name="user_id",
    )

    # OAuth provider info
    type: Mapped[str] = mapped_column(String(255), nullable=False)
    provider: Mapped[str] = mapped_column(String(255), nullable=False)
    provider_account_id: Mapped[str] = mapped_column(
        String(255), nullable=False, name="provider_account_id"
    )

    # OAuth tokens
    refresh_token: Mapped[str | None] = mapped_column(Text, nullable=True)
    access_token: Mapped[str | None] = mapped_column(Text, nullable=True)
    expires_at: Mapped[int | None] = mapped_column(Integer, nullable=True)
    token_type: Mapped[str | None] = mapped_column(String(255), nullable=True)
    scope: Mapped[str | None] = mapped_column(String(255), nullable=True)
    id_token: Mapped[str | None] = mapped_column(Text, nullable=True)
    session_state: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Relationship to User
    user: Mapped["User"] = relationship("User", back_populates="accounts")

    # Unique constraint on provider + providerAccountId
    __table_args__ = (
        {"extend_existing": True},
    )

    def __repr__(self) -> str:
        return f"<Account(id={self.id}, provider='{self.provider}', user_id='{self.user_id}')>"
