"""
Item model - mirrors the frontend Prisma Item schema.

This is an example domain model for CRUD operations.
Items are associated with users who create them.
"""

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Item(Base):
    """
    Item model matching the frontend Prisma Item schema.

    Table name: 'items' (matches Prisma @@map("items"))

    Example domain model for demonstrating CRUD operations.
    Each item belongs to a user.
    """

    __tablename__ = "items"

    # Primary key - UUID generated by Prisma
    id: Mapped[str] = mapped_column(String(36), primary_key=True)

    # Item content
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Status: DRAFT or PUBLISHED
    status: Mapped[str] = mapped_column(String(50), default="DRAFT", nullable=False)

    # Foreign key to User
    user_id: Mapped[str] = mapped_column(
        String(25),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        name="user_id",
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        name="created_at",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        name="updated_at",
    )

    # Relationship to User
    user: Mapped["User"] = relationship("User", back_populates="items")

    def __repr__(self) -> str:
        return f"<Item(id={self.id}, title='{self.title}', status='{self.status}')>"
