"""
Session model - mirrors the frontend Prisma Session schema.

This model stores user session information for NextAuth.js.
Note: When using JWT strategy, sessions may not be stored in the database,
but this model is kept for compatibility with database session strategy.
"""

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Session(Base):
    """
    Session model matching the frontend Prisma Session schema.

    Table name: 'sessions' (matches Prisma @@map("sessions"))

    Stores session tokens and expiration times.
    Used when NextAuth is configured with database session strategy.
    """

    __tablename__ = "sessions"

    # Primary key - CUID generated by Prisma
    id: Mapped[str] = mapped_column(String(25), primary_key=True)

    # Session token (unique identifier for the session)
    session_token: Mapped[str] = mapped_column(
        String(255), unique=True, nullable=False, name="session_token"
    )

    # Foreign key to User
    user_id: Mapped[str] = mapped_column(
        String(25),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        name="user_id",
    )

    # Session expiration
    expires: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Relationship to User
    user: Mapped["User"] = relationship("User", back_populates="sessions")

    def __repr__(self) -> str:
        return f"<Session(id={self.id}, user_id='{self.user_id}', expires='{self.expires}')>"
