"""
User model for authentication.

The backend is the sole owner of user data. Users are created during
OAuth authentication and queried for JWT token validation.
"""

from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Enum as SAEnum, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.account import Account
    from app.models.comment import Comment
    from app.models.poll import Poll
    from app.models.poll_comment import PollComment
    from app.models.post import Post
    from app.models.post_like import PostLike
    from app.models.session import Session
    from app.models.vote import Vote


class Role(str, Enum):
    """User roles matching Prisma enum."""

    USER = "USER"
    ADMIN = "ADMIN"


class User(Base):
    """
    User model.

    Table name: 'users'

    Users are created by the backend auth service during OAuth login.
    """

    __tablename__ = "users"

    # Primary key - CUID generated by Prisma
    id: Mapped[str] = mapped_column(String(25), primary_key=True)

    # User info
    name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    email: Mapped[str | None] = mapped_column(String(255), nullable=True, unique=True, index=True)
    email_verified: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, name="email_verified"
    )
    hashed_password: Mapped[str | None] = mapped_column(String(255), nullable=True, name="hashed_password")
    image: Mapped[str | None] = mapped_column(String(1000), nullable=True)

    # Role (PostgreSQL enum type "Role")
    role: Mapped[str] = mapped_column(
        SAEnum(Role, name="Role", create_type=False),
        default=Role.USER,
        nullable=False,
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, name="created_at"
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=func.now(), server_default=func.now(), onupdate=func.now(), nullable=False, name="updated_at"
    )

    # Relationships (matching Prisma schema)
    accounts: Mapped[list["Account"]] = relationship(
        "Account", back_populates="user", cascade="all, delete-orphan"
    )
    sessions: Mapped[list["Session"]] = relationship(
        "Session", back_populates="user", cascade="all, delete-orphan"
    )
    posts: Mapped[list["Post"]] = relationship(
        "Post", back_populates="user", cascade="all, delete-orphan"
    )
    comments: Mapped[list["Comment"]] = relationship(
        "Comment", back_populates="user", cascade="all, delete-orphan"
    )
    post_likes: Mapped[list["PostLike"]] = relationship(
        "PostLike", back_populates="user", cascade="all, delete-orphan"
    )

    # Poll relationships
    polls: Mapped[list["Poll"]] = relationship(
        "Poll", back_populates="user", cascade="all, delete-orphan"
    )
    poll_comments: Mapped[list["PollComment"]] = relationship(
        "PollComment", back_populates="user", cascade="all, delete-orphan"
    )
    # votes relationship removed — votes.user_id no longer has FK to users

    def __repr__(self) -> str:
        return f"<User(id={self.id}, email='{self.email}', role='{self.role}')>"
