"""
User model for authentication - mirrors the frontend Prisma User schema.

This model allows the backend to query user information from the shared database
after validating the JWT token from NextAuth.
"""

from datetime import datetime
from enum import Enum

from sqlalchemy import DateTime, String, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class Role(str, Enum):
    """User roles matching Prisma enum."""

    USER = "USER"
    ADMIN = "ADMIN"


class User(Base):
    """
    User model matching the frontend Prisma User schema.

    Table name: 'users' (matches Prisma @@map("users"))

    This model is read-only from the backend's perspective.
    User creation/management is handled by the frontend (NextAuth).
    The backend uses this to fetch user details after JWT validation.
    """

    __tablename__ = "users"

    # Primary key - CUID generated by Prisma
    id: Mapped[str] = mapped_column(String(25), primary_key=True)

    # User info
    name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    email: Mapped[str | None] = mapped_column(String(255), nullable=True, unique=True, index=True)
    email_verified: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, name="email_verified"
    )
    hashed_password: Mapped[str | None] = mapped_column(String(255), nullable=True, name="hashed_password")
    image: Mapped[str | None] = mapped_column(String(1000), nullable=True)

    # Role
    role: Mapped[str] = mapped_column(String(10), default=Role.USER.value, nullable=False)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, name="created_at"
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False, name="updated_at"
    )

    def __repr__(self) -> str:
        return f"<User(id={self.id}, email='{self.email}', role='{self.role}')>"
